### PR TITLE
FIX: Parse long args with '=' in value (#47)

### LINKED ISSUE #47: Everything after "=" gets stripped off in long args with "=" in value
When an arg has `=` in the value, everything after (inc) `=` gets stripped off from the arg.

Pass this command to `arg()` —
```sh
yarn keystone dev --connect-to=mongodb://user:pass@localhost:27017/keystone?authSource=admin&w=1
```

**Current output**
`--connect-to` = `mongodb://user:pass@localhost:27017/keystone?authSource`

**Expected output**
`--connect-to` = `mongodb://user:pass@localhost:27017/keystone?authSource=admin&w=1`

This is essential for passing URLs as arg value.

### PR DESCRIPTION
**Pull request by flexdinesh**
Fixes #47

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ function arg(opts, {argv = process.argv.slice(2), permissive = false, stopAtPosi
 
 			for (let j = 0; j < separatedArguments.length; j++) {
 				const arg = separatedArguments[j];
-				const [originalArgName, argStr] = arg[1] === '-' ? arg.split('=', 2) : [arg, undefined];
+				const [originalArgName, argStr] = arg[1] === '-' ? arg.split(new RegExp('=(.+)'), 2) : [arg, undefined];
```
Comment (Qix-) [inline index.js]:
```suggestion
				const [originalArgName, argStr] = arg[1] === '-' ? arg.split(/=(.*)/, 2) : [arg, undefined];
```

Just use the regex syntax here.

Also, use `.*` since we need to guarantee two arguments are always returned. With `.+`, only one is returned if the argument is `--foo=`, which would throw an array destructuring error.

Comment (flexdinesh) [reply index.js]: @Qix- I have made the changes and pushed a new commit
- `.+` changed to `.*`
- Used `/[=](.*)/` instead of `/=(.*)/` 'cos of lint rule [no-div-regex](https://eslint.org/docs/rules/no-div-regex)

File: index.js [hunk 2]
```diff
@@ -73,7 +73,7 @@ function arg(opts, {argv = process.argv.slice(2), permissive = false, stopAtPosi
 
 			for (let j = 0; j < separatedArguments.length; j++) {
 				const arg = separatedArguments[j];
-				const [originalArgName, argStr] = arg[1] === '-' ? arg.split('=', 2) : [arg, undefined];
+				const [originalArgName, argStr] = arg[1] === '-' ? arg.split(/[=](.*)/, 2) : [arg, undefined];
```
Comment (Qix-) [inline index.js]:
```suggestion
				const [originalArgName, argStr] = arg[1] === '-' ? arg.split(/=(.*)/, 2) : [arg, undefined];
```

Why the character class?

Comment (Qix-) [reply index.js]: Ah Just saw your other comment. We can disable that linting rule, we're all grownups here and can discern between division and regexes...

File: index.js (hunk 1 above)
Comment (Qix-) [reply index.js]: See https://github.com/zeit/arg/pull/48#discussion_r302926360

File: index.js (hunk 2 above)
Comment (flexdinesh) [reply index.js]: Because there's a lint rule (probably from xo) that prevents using `/=(.*)/` and throws `no-div-regex` while running tests. I referred [no-div-regex](https://eslint.org/docs/rules/no-div-regex) for changes.

**Comment by Qix-** [comment]
Oh wow, my understanding of `.split(x, n)` has been completely off. I suppose I assumed it worked like Java's, where it would stop splitting after `n` splits and put the rest in the last element. As it stands, the second parameter seems a bit useless IMO.

Thanks for this, it's a great catch.

File: index.js (hunk 2 above)
Comment (Qix-) [reply index.js]: Commenting to make sure the Github refresh bug didn't prevent you from seeing https://github.com/zeit/arg/pull/48#discussion_r302926360 @flexdinesh :)

Comment (Qix-) [reply index.js]: Should just be `{"xo": {"rules": {"no-div-regex": 0}}}` in `package.json` and then removing the `[]` around `[=]`.

**Comment by flexdinesh** [comment]
> As it stands, the second parameter seems a bit useless IMO.
Second param is definitely useless as far as I observe as well. When I remove it, all tests pass. Do you want me to remove the second param as well as part of this PR?

**Comment by Qix-** [comment]
No because it's actually necessary to get it to work as expected.

```
> (x => x.split(/=(.*)/, 2))('--foo=qux=qox')
[ '--foo', 'qux=qox' ]
> (x => x.split(/=(.*)/))('--foo=qux=qox')
[ '--foo', 'qux=qox', '' ]
```

We have to have **exactly** 2 elements for the destructure to work.

What a weird API. Javascript is weird.

File: index.js (hunk 2 above)
Comment (flexdinesh) [reply index.js]: Lint rule removed and regex updated in a new commit

**Comment by Qix-** [comment]
Great, thank you so much!

**Comment by Qix-** [comment]
Published as `4.1.1`.
